ebasket/urls.py
from django.contrib import admin
from django.urls import path,include
from store.views import *
from ebasket import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",index),
    path("Ebasket",include(("store.urls","store"),namespace="stores"))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from .import views

urlpatterns=[
    path("-index",views.index,name="index1"),
   path("-register",views.regis,name="register1"),
   path("-login",views.loginn,name="logins"),
   path("logout",views.logoutt,name="logout"),
   path("-addcart/<int:pk>",views.cart,name="addcart"),
   path("-showcart",views.show_Cart,name="showcart"),
   path("delete/<int:proid>",views.delete,name='delete'),
   path("minuscart/<int:pid>",views.minus_cart,name="minuscart"),
   path("pluscart/<int:pid>",views.plus_cart,name="pluscart")
]

store/models.py
from django.db import models
from django.contrib.auth.models import User
class Categories(models.Model):
    name=models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Product(models.Model):
    title= models.CharField(max_length=30)
    price=models.IntegerField(default='0')
    description=models.CharField(max_length=300)
    image=models.ImageField(upload_to='image/')
    category=models.ForeignKey(Categories,on_delete=models.CASCADE, default='')

    def __str__(self):
        return self.title


class Cart(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    product=models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    amount=models.IntegerField(default=0)
    total_amount=models.IntegerField(default=0)
    
    def total_cost(self):
        return self.quantity*self.product.price 

store/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core import validators
from .models import *
class RegisterForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}))
    # first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'}), max_length=32, help_text='First name')
    # last_name=forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}), max_length=32, help_text='Last name')
    email=forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}), max_length=64, help_text='Enter a valid email address',required=True,validators=[validators.EmailValidator(message="Invalid Email")])
    password1=forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))
    password2=forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password Again'}))

    class Meta():
        model = User
        fields = ["username","email", "password1", "password2"]


class LoginForm(forms.Form):
    username=forms.CharField(max_length=30,widget=forms.TextInput(attrs={'class':'form-control'}))
    password=forms.CharField(max_length=30,widget=forms.PasswordInput(attrs={'class':'form-control'}))


class CartItem(forms.ModelForm):
    class Meta:
        model=Cart
        fields="__all__"

store/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from .models import *
from .forms import *
from django.contrib.auth import authenticate,login,logout




def index(request):
    products=Product.objects.all()
    category=Categories.objects.all()
    cat_id=request.GET.get('categories')
    if cat_id:
        product=Product.objects.filter(id=cat_id)
    else:
        products=Product.objects.all()
    d={'product':products,'category':category}
    return render(request,"index.html",d)

def regis(request):
    if request.method=='POST':
        obj=RegisterForm(request.POST)
        obj.save()
        return redirect("/Ebasket-login")
    else:
        d={'form':RegisterForm}
        return render(request,'register.html',d)
    

def loginn(request):
    if request.method=='POST':
        uname=request.POST.get("username")
        passwd=request.POST.get("password")
        user=authenticate(request,username=uname,password=passwd)
        if user is not None:
            request.session["id"]=user.id 
            print(request.session.get("id"))
            login(request,user)
            return redirect("/")
        else:
            d={'form':LoginForm}
            return render(request,'login.html',d)
    else:
            d={'form':LoginForm}
            return render(request,'login.html',d)

def logoutt(request):
    logout(request)
    return redirect("/")  

def cart(request,pk):
    user_id=request.session.get("id")
    user=request.user
    product=Product.objects.get(id=pk)
    Cart(user=user,product=product).save()
    return redirect("/")

def show_Cart(request):
     ids=request.session.get("id")

     obj=Cart.objects.filter(user=ids)
     amount=0
     value=0
     for p in obj:
            
            value= p.quantity * p.product.price
            amount= value + amount
     total_amount= amount +50
  
     d={'data':obj,'total_amount':total_amount,'amount':amount}
     return render(request,'cart.html',d)

def plus_cart(request,pid):
    if request.method=="GET":
        c=Cart.objects.get(id=pid)
        c.quantity +=1
        c.save()
        user=request.user
        cart=Cart.objects.filter(user=user)
        for p in cart:
            amount=0
            value= p.quantity * p.product.price
            amount= value + amount
        total_amount= amount + 50
        data={
            "quantity":c.quantity,
            "amount":c.amount,
            "totalamount":c.total_amount
        }
        return redirect("/Ebasket-showcart")

def minus_cart(request,pid):
    if request.method=="GET":
        c=Cart.objects.get(id=pid)
        c.quantity -=1
        c.save()
        user=request.user
        cart=Cart.objects.filter(user=user)
        for p in cart:
            amount=0
            value= p.quantity * p.product.price
            amount= value + amount
        total_amount= amount + 50
        data={
            "quantity":c.quantity,
            "amount":c.amount,
            "totalamount":c.total_amount
        }
        return redirect("/Ebasket-showcart")




def delete(request,proid):
    obj=Cart.objects.get(id=proid)
    obj.delete()
    return redirect("/Ebasket-showcart")

store/templates/cart.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Order Your Coffee!</title>
    <link rel="stylesheet" href="{%static 'css/main.css' %}">
    <link rel="stylesheet" href="{%static 'css/my.css' %}">
</head>
<body>
    {%include 'navbar.html'%}
    <div class="container my-5">
        <div class="row">
            {% if data %}
            <h1 class="text-center mb-5">Shopping Cart</h1>
            <div class="col-sm-8">
                <div class="card">
                    <div class="card-body">
                        <h3>Cart</h3>
                        {% for i in data %}
                        <div class="row">
                            <div class="col-sm-3 text-center align-self-center"><img src="{{i.product.image.url}}" alt="" class="img-fluid img-thumbnail shadow-sm" height="150" width="150"></div>
                            <div class="col-sm-9">
                                <div><h5>{{i.product.title}}</h5>
                                    <p class="mb-2 text-muted small">{{i.product.description}}</p>
                                    <div class="my-3">
                                        <label for="quantity" >Quantity</label>
                                        <a href="{%url 'stores:minuscart' i.id %}" name="pid" class="minus-cart btn" pid="{{i.product.id}}"><i class="fas fa-minus-square fa-lg">-</i>
                                        </a>
                                        <span id="quantity">{{i.quantity}}</span>
                                        <a href="{%url 'stores:pluscart' i.id %}" name='pid' class="plus-cart btn" pid="{{i.product.id}}"><i class="fas fa-plus-square fa-lg">+</i></a>
                                    </div>
                                    <div class="d-flex justify-content-between">
                                     <a href="{%url 'stores:delete' i.id %}" class="remove-cart btn btn-sm btn-secondary mr-3" name="proid"   proid="{{i.product.id}}">Remove</a>
                                        
                                        
                            
                                    </div>
                                </div>
                            </div> 
                        </div>
                        <hr class="text-muted">
                        {% endfor %}
                    </div>
                </div>
            </div>
            
            <div class="col-sm-4">
                <div class="card">
                    <div class="card-body">
                        <h3>Total Amount Of</h3>
                        <ul class="list-group">
                            <li class="list-group item d-flex justify-content-between align-item-center border-0 px-0 pb-0">Amount <span id="amount" >Rs.{{amount}}</span></li>
                            <li class="list-group item d-flex justify-content-between align-item-center border-0 px-0">Shipping <span>Rs.50</span></li>
                            <li class="list-group item d-flex justify-content-between align-item-center border-0 px-0 nb-3">
                                <div> 
                                    <strong>Total</strong> <small>(Including GST)</small>
                                </div>
                                <span id="totalamount"><strong>Rs.{{total_amount}}</strong></span>
                            </li>
                        </ul>
                        <div class="d-grid"><a href="#" class="btn btn-primary">Place Order</a></div>
                    </div>
                </div>
            </div>
            {% else %}
            <h1 class="text-center nb-5"> Cart Is Empty</h1>
           {% endif %}
        </div>
    </div>


    <link rel="stylesheet" href="{%static 'js/main.js' %}">
</body>
</html>

store/templates/index.html
<!doctype html>
<html lang="en">

<head>
    {%load static%}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Hello, world!</title>
</head>

<body>
    <div class="container-fluid">
        {%include 'navbar.html' %}
    </div>

    <div class="container-fluid mt-3">
        <div class="row">
            <div class="col-lg-2 mx-auto">
                <div class="list-group">
                    {%for j in category%}
                    <a href="/?categories={{j.id}}" class="list-group-item list-group-item-action">{{j.name}}</a>
                     {%endfor%}
                </div>
            </div>
            <div id="products" class="col-lg-10 mx-auto">
                <div class="row mx-auto">
                    {% for product in product %}
                    <div class="card mx-auto mb-3" style="width: 18rem;">
                        <img src="{{ product.image.url }}" class="card-img-top">
                        <div class="card-body">
                            <h5 class="card-title">{{product.title}}</h5>
                            <p class="card-text">{{product.category}}</p>
                            <p class="card-text"><b>Rs.{{product.price}}/-</b></p>
                            <p class="card-text">{{product.description}}</p>
                            <a href="{%url 'stores:addcart' product.id%}"><button>Add Cart</button></a>
                         
                        </div>
                    </div>

                    {% endfor %}
                </div>
            </div>
        </div>

    </div>




    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

</body>

</html>

store/templates/login.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  </head>
  <body>
    <div class="container-fluid">
        {%include 'navbar.html' %}
    </div>
<div class="container mx-auto">
    <form action="" method="post">
        {%csrf_token%}
        <table>
            {%for i in form%}
              <div class="mt-2"> {{i.label}} </div> {{i}}
            {% endfor %}
         <div class="mt-3">
            <tr>
              <td><input class="btn btn-success mt-2 " type="submit" value="Submit"></td>
              <td><input class="btn btn-success mt-2" type="reset" value="Reset"></td>
            </tr>
            </div>
        </table>
    </form>
    </div>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </body>
</html>

store/templates/navbar.html
<!doctype html>
<html lang="en">
  <head>
    {%load static%}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  </head>
  <body>


<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">
        <img src="{%static 'pictures/sd.png' %}" width="100" height="80" alt="">
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{%url 'stores:index1' %}">Home</a>
          </li>

          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{%url 'stores:index1' %}">About Us</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="#">Contact Us</a>
          </li>

          {% if user.is_authenticated%}
          <li class="nav-item">
            <a class="nav-link " href="{%url 'stores:showcart' %}">Cart</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{%url 'stores:logout' %}">Logout</a>
          </li>
          <li class="nav-item">
            <h3> {{user}}</h3>
          </li>
          {%else%}
          <li class="nav-item">
            <a class="nav-link " href="{%url 'stores:register1' %}">Register</a> 
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{%url 'stores:logins' %}">Login</a>
          </li>
         

          {%endif%}
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>
</html>

store/templates/register.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Bootstrap demo</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>

<body>
  <div class="container-fluid">
    {%include 'navbar.html' %}
  </div>
  <div class="container mx-auto">
   <form  method="post">
    {%csrf_token%}
    <table>
      {%for i in form%}
      <div class="mt-2"> {{i.label}} </div> {{i}}
      {% endfor %}
      <div class="mt-3">
        <tr>
          <td> <button type="submit" class="btn btn-danger" value="Submit">Submit</button></td>
          <td> <button type="reset" class="btn btn-info" value="Reset">Reset</button></td>
        </tr>
      </div>
    </table>
    </form>
  </div>



  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
    crossorigin="anonymous"></script>
</body>

</html>